spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping-app?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

#SMTP configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  